server.port=8181
server.servlet.context-path=/restroly
spring.application.name=RestroHub
spring.datasource.url=jdbc:postgresql://localhost:5432/restrohub_db
spring.datasource.username=postgres
spring.datasource.password=abhi244
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:3002