# src/main/resources/templateConfig.properties

restroly.excel.template-path=assets/Menu_Template.xlsx

restroly.excel.food-mapping.Food\ Name=name
restroly.excel.food-mapping.Description=desc
restroly.excel.food-mapping.Price=price
restroly.excel.food-mapping.Is\ Veg=isVeg
restroly.excel.food-mapping.Is\ Available=isAvailable
restroly.excel.food-mapping.Image\ URL=imageUrl